# Generated by Django 5.0 on 2024-03-05 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_conexion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='Person',
        ),
    ]
